FORMAT: 1A
HOST: http://wsdl.sync.today/api

# Sync.Today
Sync.Today is tasks, calendars, contacts and documents synchronization engine. We magically synchronize tasks, calendars, contacts and documents. Sounds boring, but is useful. You never see our product, just the results 

# Group Accounts
Accounts related resources of the **Sync.Today API**

## Accounts Collection [/accounts]
### List all Accounts [GET]
+ Response 200 (application/json)

            [
                  {
                  "InternalId": "30e7cb68-3804-4c45-806a-1457ef318183",
                  "IsBlocked": false,
                  "Name_FirstName": null,
                  "Name_Surname": null,
                  "ContactPerson_Email": null,
                  "BelongsToUser": "93bc7618-4db0-4bc2-ac1e-0244e082d141",
                  "AccountAssemblyName": "naseukolycz.universalsync.communicator.exchange, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                  "UpdatesPolicy":       {
                     "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0
                  },
                  "LastSync":       {
                     "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00"
                  },
                  "ConnectInfo":       {
                     "InternalId": "30e7cb68-3804-4c45-806a-1457ef318183",
                     "BelongsToUser": "93bc7618-4db0-4bc2-ac1e-0244e082d141",
                     "Username": "tester@naseukolycz.onmicrosoft.com",
                     "Password": "v7xe+sgloF78dZqlIOaQGA==",
                     "Server": "",
                     "AccountAssemblyName": "naseukolycz.universalsync.communicator.exchange, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                     "UpdatesPolicy":          {
                        "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                        "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                        "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                        "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                        "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                        "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0
                     },
                     "LastSync":          {
                        "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                        "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                        "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                        "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                        "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                        "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00"
                     },
                     "IsBlocked": false
                  },
                  "ExternalId": "Empty-635403248552454115",
                  "LastModified": "2014-07-07T08:14:15.247Z"
               },
                  {
                  "InternalId": "30e7cb68-3804-4c45-806a-1457ef318183",
                  "IsBlocked": false,
                  "Name_FirstName": null,
                  "Name_Surname": null,
                  "ContactPerson_Email": null,
                  "BelongsToUser": "93bc7618-4db0-4bc2-ac1e-0244e082d141",
                  "AccountAssemblyName": "naseukolycz.universalsync.communicator.exchange, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                  "UpdatesPolicy":       {
                     "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0
                  },
                  "LastSync":       {
                     "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00"
                  },
                  "ConnectInfo":       {
                     "InternalId": "30e7cb68-3804-4c45-806a-1457ef318183",
                     "BelongsToUser": "93bc7618-4db0-4bc2-ac1e-0244e082d141",
                     "Username": "tester@naseukolycz.onmicrosoft.com",
                     "Password": "v7xe+sgloF78dZqlIOaQGA==",
                     "Server": "",
                     "AccountAssemblyName": "naseukolycz.universalsync.communicator.exchange, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                     "UpdatesPolicy":          {
                        "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                        "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                        "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                        "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                        "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                        "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0
                     },
                     "LastSync":          {
                        "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                        "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                        "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                        "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                        "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                        "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00"
                     },
                     "IsBlocked": false
                  },
                  "ExternalId": "Empty-635403248552454115",
                  "LastModified": "2014-07-07T08:14:15.247Z"
               }
            ]

### Create an Account [POST]
+ Request (application/json)

            {
               "InternalId": "30e7cb68-3804-4c45-806a-1457ef318183",
               "IsBlocked": false,
               "Name_FirstName": null,
               "Name_Surname": null,
               "ContactPerson_Email": null,
               "BelongsToUser": "93bc7618-4db0-4bc2-ac1e-0244e082d141",
               "AccountAssemblyName": "naseukolycz.universalsync.communicator.exchange, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
               "UpdatesPolicy":    {
                  "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0
               },
               "LastSync":    {
                  "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00"
               },
               "ConnectInfo":    {
                  "InternalId": "30e7cb68-3804-4c45-806a-1457ef318183",
                  "BelongsToUser": "93bc7618-4db0-4bc2-ac1e-0244e082d141",
                  "Username": "tester@naseukolycz.onmicrosoft.com",
                  "Password": "v7xe+sgloF78dZqlIOaQGA==",
                  "Server": "",
                  "AccountAssemblyName": "naseukolycz.universalsync.communicator.exchange, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                  "UpdatesPolicy":       {
                     "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0
                  },
                  "LastSync":       {
                     "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00"
                  },
                  "IsBlocked": false
               },
               "ExternalId": "Empty-635403248552454115",
               "LastModified": "2014-07-07T08:14:15.247Z"
            }


+ Response 201 (application/json)

            {
               "InternalId": "30e7cb68-3804-4c45-806a-1457ef318183",
               "IsBlocked": false,
               "Name_FirstName": null,
               "Name_Surname": null,
               "ContactPerson_Email": null,
               "BelongsToUser": "93bc7618-4db0-4bc2-ac1e-0244e082d141",
               "AccountAssemblyName": "naseukolycz.universalsync.communicator.exchange, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
               "UpdatesPolicy":    {
                  "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0
               },
               "LastSync":    {
                  "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00"
               },
               "ConnectInfo":    {
                  "InternalId": "30e7cb68-3804-4c45-806a-1457ef318183",
                  "BelongsToUser": "93bc7618-4db0-4bc2-ac1e-0244e082d141",
                  "Username": "tester@naseukolycz.onmicrosoft.com",
                  "Password": "v7xe+sgloF78dZqlIOaQGA==",
                  "Server": "",
                  "AccountAssemblyName": "naseukolycz.universalsync.communicator.exchange, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                  "UpdatesPolicy":       {
                     "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0
                  },
                  "LastSync":       {
                     "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00"
                  },
                  "IsBlocked": false
               },
               "ExternalId": "Empty-635403248552454115",
               "LastModified": "2014-07-07T08:14:15.247Z"
            }
            
## Account [/accounts/{InternalId}]
A single Account object with all its details

+ Parameters
    + InternalId (required, Guid, `93bc7618-4db0-4bc2-ag1e-0244e082d141`) ... Guid `InternalId` of the Account to perform action with. Has example value.

### Retrieve a Account [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            {
               "InternalId": "30e7cb68-3804-4c45-806a-1457ef318183",
               "IsBlocked": false,
               "Name_FirstName": null,
               "Name_Surname": null,
               "ContactPerson_Email": null,
               "BelongsToUser": "93bc7618-4db0-4bc2-ac1e-0244e082d141",
               "AccountAssemblyName": "naseukolycz.universalsync.communicator.exchange, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
               "UpdatesPolicy":    {
                  "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                  "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0
               },
               "LastSync":    {
                  "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                  "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00"
               },
               "ConnectInfo":    {
                  "InternalId": "30e7cb68-3804-4c45-806a-1457ef318183",
                  "BelongsToUser": "93bc7618-4db0-4bc2-ac1e-0244e082d141",
                  "Username": "tester@naseukolycz.onmicrosoft.com",
                  "Password": "v7xe+sgloF78dZqlIOaQGA==",
                  "Server": "",
                  "AccountAssemblyName": "naseukolycz.universalsync.communicator.exchange, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                  "UpdatesPolicy":       {
                     "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0,
                     "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": 0
                  },
                  "LastSync":       {
                     "naseukolycz.universalsync.icommunicator.NuContact, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuTask, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuRecurringEvent, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.icommunicator.NuProject, naseukolycz.universalsync.icommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00",
                     "naseukolycz.universalsync.idata.NuUser, naseukolycz.universalsync.idata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null": "2014-07-06T11:14:15+02:00"
                  },
                  "IsBlocked": false
               },
               "ExternalId": "Empty-635403248552454115",
               "LastModified": "2014-07-07T08:14:15.247Z"
            }
            
### Remove an Account [DELETE]
+ Response 204


# Group Relations
Relations related resources of the **Sync.Today API**

## Relations Collection [/relations]
### List all Relations [GET]
+ Response 200 (application/json)

            [{
               "Id": 2,
               "InternalId": "65299bb8-aa80-473e-bce1-0850fe34b785",
               "UserId": 1
            }]

### Create a Relation [POST]
+ Request (application/json)

            {
               "Id": 2,
               "InternalId": "65299bb8-aa80-473e-bce1-0850fe34b785",
               "UserId": 1
            }


+ Response 201 (application/json)

            {
               "Id": 2,
               "InternalId": "65299bb8-aa80-473e-bce1-0850fe34b785",
               "UserId": 1
            }

## Relation [/relations/{InternalId}]
A single Relation object with all its details

+ Parameters
    + InternalId (required, Guid, `93bc7618-4db0-4bc2-ag1e-0244e082d141`) ... Guid `InternalId` of the Relation to perform action with. Has example value.

### Retrieve a Relation [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            {
               "Id": 2,
               "InternalId": "65299bb8-aa80-473e-bce1-0850fe34b785",
               "UserId": 1
            }
            
### Remove a Relation [DELETE]
### Remove an Account [DELETE]
+ Response 204

# Group Users
Users related resources of the **Sync.Today API**

## Users Collection [/users]
### List all Users [GET]
+ Response 200 (application/json)

        [
          {
          "InternalId": "dab86083-3a99-4873-8c57-eb0a648fee35",
          "Created": "2014-05-26T12:56:37Z",
          "IsBlocked": false,
          "Maintenance": -1,
          "FirstName": "Jan",
          "LastName": "Krb",
          "Email": "jan.krb@naseukoly.cz",
          "Password": "10:AAA:BBB",
          "EventsInRelation": {},
          "BelongsToUser": "00000000-0000-0000-0000-000000000000"
           },
              {
              "InternalId": "61fb446d-9a68-95e7-6104-75eaf0a6c8a6",
              "Created": "2014-07-07T11:15:19.207Z",
              "IsBlocked": false,
              "Maintenance": -1,
              "FirstName": null,
              "LastName": null,
              "Email": "0",
              "Password": "13:UUU:WWW",
              "EventsInRelation": {},
              "BelongsToUser": "00000000-0000-0000-0000-000000000000"
        }]

### Create a User [POST]
+ Request (application/json)

        {
           "InternalId": "93bc7618-4db0-4bc2-ag1e-0244e082d141",
           "Created": "2014-06-07T08:14:14Z",
           "IsBlocked": false,
           "Maintenance": 0,
           "FirstName": "John",
           "LastName": "Rambo",
           "Email": "a@b.cz",
           "Password": "10:EJYnWHc:TxnQDjW1",
           "EventsInRelation": {},
           "BelongsToUser": "00000000-0000-0000-0000-000000000000"
        }


+ Response 201 (application/json)

        {
           "InternalId": "93bc7618-4db0-4bc2-ag1e-0244e082d141",
           "Created": "2014-06-07T08:14:14Z",
           "IsBlocked": false,
           "Maintenance": 0,
           "FirstName": "John",
           "LastName": "Rambo",
           "Email": "a@b.cz",
           "Password": "10:EJYnWHc:TxnQDjW1",
           "EventsInRelation": {},
           "BelongsToUser": "00000000-0000-0000-0000-000000000000"
        }

## User [/users/{InternalId}]
A single User object with all its details

+ Parameters
    + InternalId (required, guid, `93bc7618-4db0-4bc2-ag1e-0244e082d141`) ... Guid `InternalId` of the User to perform action with. Has example value.

### Retrieve a User [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            {
               "InternalId": "93bc7618-4db0-4bc2-ag1e-0244e082d141",
               "Created": "2014-06-07T08:14:14Z",
               "IsBlocked": false,
               "Maintenance": 0,
               "FirstName": "John",
               "LastName": "Rambo",
               "Email": "a@b.cz",
               "Password": "10:EJYnWHc:TxnQDjW1",
               "EventsInRelation": {},
               "BelongsToUser": "00000000-0000-0000-0000-000000000000"
            }
            
### Remove a User [DELETE]
+ Response 204


#Group NuTasks

## NuTask Collection [/nutask]
Returns all NuTask entities from database.
### List of all NuTasks [GET]
+ Response 200 (application/json)

        [
         {
         "Subject": "wefwefwef",
         "Body": "wefwefwef",
         "StartDate": "2014-02-26T13:00:00Z",
         "DueDate": "2014-02-28T15:00:00Z",
         "Reminder": "2014-07-10T13:45:00Z",
         "Priority": 0,
         "IsPrivate": true,
         "Company": "fewf",
         "Completed": true,
         "ProjectName": "?",
         "Parents": [{
         "Subject": "thzčz",
         "Body": "čřzčřz",
         "StartDate": "2014-07-07T14:52:38.537",
         "DueDate": "2014-07-07T14:52:38.537",
         "Reminder": "2014-07-07T14:52:38.537",
         "Priority": 0,
         "IsPrivate": true,
         "Company": "rtgerg",
         "Completed": true,
         "ProjectName": "ergerg",
         "Parents": [],
         "ExternalId": "d628ef3d-f47d-4468-be0f-e82ca1d6543e",
         "LastModified": "2014-07-07T14:52:38.537"
         }],
         "ExternalId": "0e28ef3d-f47d-4468-be0f-e82ca1d6543e",
         "LastModified": "2014-07-07T12:52:38.537Z"
         },
         {
         "Subject": "wefwefwef",
        "Body": "wefwefwef",
         "StartDate": "2014-02-26T13:00:00Z",
         "DueDate": "2014-02-28T15:00:00Z",
         "Reminder": "2014-07-10T13:45:00Z",
         "Priority": 0,
         "IsPrivate": true,
         "Company": "fewf",
         "Completed": true,
         "ProjectName": "?",
         "Parents": [{
             "Subject": "thzčz",
             "Body": "čřzčřz",
             "StartDate": "2014-07-07T14:52:38.537",
             "DueDate": "2014-07-07T14:52:38.537",
             "Reminder": "2014-07-07T14:52:38.537",
             "Priority": 0,
             "IsPrivate": true,
             "Company": "rtgerg",
             "Completed": true,
             "ProjectName": "ergerg",
             "Parents": [],
             "ExternalId": "d628ef3d-f47d-4468-be0f-e82ca1d6543e",
             "LastModified": "2014-07-07T14:52:38.537"
              }],
         "ExternalId": "1e28ef3d-f47d-4468-be0f-e82ca1d6543e",
         "LastModified": "2014-07-07T12:52:38.537Z"
         }]
         
## NuTask  [/nutask{?id,accountId}]
Returns the NuTask entity by its ExternalId.

+ Parameters
    + id (required, string) ... This parameter is ExternalId of entity (NuTask).
    + accountId (required, string) ... Entity belongs to account. This parameter is important because in database can be more entities with same ExternalId. 

### Retrieve NuTask by externalId [GET]
+ Response 200 (application/json)

         {
          "Subject": "sample rest",
          "Body": "created by rest",
          "StartDate": "2014-02-26T13:00:00Z",
          "DueDate": "2014-02-28T15:00:00Z",
          "Reminder": "2014-07-10T13:45:00Z",
          "Priority": 0,
          "IsPrivate": true,
          "Company": "fewf",
          "Completed": true,
          "ProjectName": "some project name",
          "Parents": [],
          "ExternalId": "2028ef3d-f47d-4468-be0f-e82ca1d6543e",
          "LastModified": "2014-07-07T12:52:38.537Z"
         }

### Update NuTask [PUT]
No value returns. Updates entity.
+ Request (application/json)

        {
         "Subject": "sample rest0002",
         "Body": "created by rest",
         "StartDate": "2014-02-26T13:00:00Z",
         "DueDate": "2014-02-28T15:00:00Z",
         "Reminder": "2014-07-10T13:45:00Z",
         "Priority": 0,
         "IsPrivate": true,
         "Company": "fewf",
         "Completed": true,
         "ProjectName": "?",
         "Parents": [],
         "ExternalId": "2028ef3d-f47d-4468-be0f-e82ca1d6543e",
         "LastModified": "2014-07-07T12:52:38.537Z"
         }


+ Response 200

### Delete NuTask [DELETE]
No returns value. Deletes entity.
 + Response 204



## NuTask [/nutask{?accountId}]
Creating NuTask.

+ Parameters
    + accountId (required, string) ... You must specify accountId because in database can be entities with same externalId.
   

### Create a NuTask [POST]

+ Request (application/json)

        {
         "Subject": "sample rest",
         "Body": "created by rest",
         "StartDate": "2014-02-26T13:00:00Z",
         "DueDate": "2014-02-28T15:00:00Z",
         "Reminder": "2014-07-10T13:45:00Z",
         "Priority": 0,
         "IsPrivate": true,
         "Company": "fewf",
         "Completed": true,
         "ProjectName": "?",
         "Parents": [],
         "ExternalId": "2028ef3d-f47d-4468-be0f-e82ca1d6543e",
         "LastModified": "2014-07-07T12:52:38.537Z"
         }


+ Response 201 (application/json)
        
        {
         "Subject": "sample rest",
         "Body": "created by rest",
         "StartDate": "2014-02-26T13:00:00Z",
         "DueDate": "2014-02-28T15:00:00Z",
         "Reminder": "2014-07-10T13:45:00Z",
         "Priority": 0,
         "IsPrivate": true,
         "Company": "fewf",
         "Completed": true,
         "ProjectName": "?",
         "Parents": [],
         "ExternalId": "2028ef3d-f47d-4468-be0f-e82ca1d6543e",
         "LastModified": "2014-07-07T12:52:38.537Z"
         }






